# Generated by Django 2.2.4 on 2019-08-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('cedula', models.CharField(max_length=11, unique=True, verbose_name='Cédula')),
                ('telefono', models.BigIntegerField(default=0, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('alive', models.BooleanField(default=True)),
            ],
        ),
    ]
